### ISSUE TITLE
Postgres 9.4 unsupported?

### ISSUE THREAD

**Issue by chr15m** [voxpelli/node-connect-pg-simple#157]
I'm getting the following error any time I try to set a session:

```
error: syntax error at or near "ON"
    at Connection.parseE (.../node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (.../node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (.../node_modules/pg/lib/connection.js:121:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)
```

I tried to extract the query from the source and run it by hand in `psql` and it yielded the same error.

```
$ psql --version
psql (PostgreSQL) 9.4.22
```

Does this mean postgres 9.4 is not supported?

**Comment by eklingman** [comment]
I'm having the same issue with `9.2.24`

**Comment by voxpelli** [comment]
Yes, since `6.0.0`: https://github.com/voxpelli/node-connect-pg-simple/blob/master/CHANGELOG.md#600-2019-07-28
