### ISSUE TITLE
param.auth becomes null if postgres password contains '/'

### ISSUE THREAD

**Issue by softsaravanacse** [voxpelli/node-connect-pg-simple#44]
**connect-pg-simple version : 4.0.0**

I am getting the following stack trace error on the latest version of connect-pg-simple. I did not have such problems  with previous  version 3.1.2. 

Suggestion : Please accept the connectString as object instead of string to fix this issue.

Stack trace error message 

/var/www/html/node_modules/connect-pg-simple/index.js:29
      const auth = params.auth.split(':');
                              ^

TypeError: Cannot read property 'split' of null
    at new PGStore (/var/www/html/node_modules/connect-pg-simple/index.js:29:31)
    at Object.<anonymous> (/var/www/html/lab2-ui/app.js:40:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/lab2-ui/bin/www:7:11)

**Comment by voxpelli** [comment]
Thank you very much for reporting!

I like the idea of supporting an object, but would like to do so in addition to the connection string so I would like to fix this bug as well.

Will try to do so as soon as possible.

**Comment by voxpelli** [comment]
@softsaravanacse Added a new option, `conObject`, and did some hardening to the `conString` parsing as well as added some tests for it all and released `4.1.0`. Does it work better for you?

**Comment by softsaravanacse** [comment]
It's working fine now. Thank you so much for a quick fix.
